FROM confluentinc/cp-kafka:5.3.1

ADD jmx-exporter-conf.yml /usr/app/jmx-exporter-conf.yml
ADD https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar /usr/app/jmx_prometheus_javaagent.jar
